# Generated by Django 3.0.5 on 2020-04-06 22:05

from django.db import migrations, models
import django.db.models.deletion
import transactions.types
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PROCESSING', 'processing'), ('COMPLETED', 'completed'), ('ERROR', 'error')], default=transactions.types.TransactionStatus['PROCESSING'], max_length=16)),
                ('location', models.CharField(choices=[('ORIGINATION_BANK', 'origination_bank'), ('ROUTABLE', 'routable'), ('DESTINATION_BANK', 'destination_bank')], default=transactions.types.TransactionLocation['ORIGINATION_BANK'], max_length=24)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.Item')),
            ],
        ),
    ]
